version: 2
updates:
  - package-ecosystem: "composer"
    directory: "backend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "frontend/"
    schedule:
      interval: "weekly"

# This looks for package.json
#  - package-ecosystem: "npm"
#    directory: "frontend/web"
#    schedule:
#      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
