site_name: echoCTF.RED Documentation
site_url:  https://echoctfred.readthedocs.io/en/latest/
site_description: A framework for developing, deploying, running and maintain CTFs
repo_url: https://github.com/echoCTF/echoCTF.RED
theme:
  name: material
  palette:
    scheme: slate          # Dark mode
    primary: lime
    primary_variant: 800   # Shade for dark mode
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
markdown_extensions:
  - smarty
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Concepts:
    - Architecture: ARCHITECTURE.md
    - Infrastructure Sizing: Infrastructure-Sizing.md
    - Onsite Infrastructure: Onsite-Infrastructure.md
  - Getting Started: Getting-Started.md
  - Installation:
    - Docker based:
      - All in one host: DOCKER-COMPOSE.md
      - All in one with separate VPN: DOCKER-COMPOSE-NOVPN.md
    - Manual installation:
      - OpenBSD General installation instructions of applications: INSTALL.md
      - Manual installation of all application on a single linux host: INSTALL-LINUX.md
  - Infrastructure:
    - Setup a Private Docker Registry: ansible/DOCKER-REGISTRY.md
    - Docker Servers Setup Guide: DOCKER-SERVERS.md
    - Docker Targets Guide: DOCKER-TARGETS.md
    - Personalize your installation: PERSONALIZING.md
    - Firewalling with PF: PF.md
  - Automation (Ansible):
    - Overview: ansible/README.md
    - Database: ansible/DB.md
    - Moderator UI: ansible/MUI.md
    - VPN Gateway: ansible/VPNGW.md
    - Participants UI playbook: ansible/PUI.md
    - Docker Servers: ansible/DOCKER-SERVERS.md
    - Docker Targets: ansible/DOCKER-TARGETS.md
    - Examples: ansible/examples.md
  - Administration:
    - Sysconfig Keys: Sysconfig-Keys.md
    - Console Commands:
      - Overview: Console-Commands.md
      - Backend:
        - Cron commands: console-commands/Cron.md
        - Player Commands: console-commands/Player.md
        - Ssl Commands: console-commands/Ssl.md
        - Sysconfig Commands: console-commands/Sysconfig.md
        - Target Commands: console-commands/Target.md
        - Metadata Commands: console-commands/Metadata.md
        - Private Network Commands: console-commands/Private-Network.md
        - User Commands: console-commands/User.md
        - VPN Commands: console-commands/Vpn.md
        - Template Commands: console-commands/Template.md
        - Sales Commands: console-commands/Sales.md
        - Maintenance Commands: console-commands/Maintenance.md
        - Tester: console-commands/Tester.md
    - Frontend:
        - Generator Commands: console-commands/Frontend_Generator.md
        - Validator Commands: console-commands/Frontend_Validator.md
        - Tester: console-commands/Tester.md

  - API: API.md
  - Guides:
      - Participants Tutorial: Participants-Tutorial.md
      - Localization: Localization.md
      - Testing: Testing.md
      - Gmail relaying: relay/Google Workspaces SMTP Setup.md
      - Use a Gmail account: Gmail.md
      - Initializing a new event repo: Initializing a new event.md
      - Firewalling details: Firewalling.md
      - Network Visuals: Network-Visuals.md
