---
CHROOT_ENV:
- "/etc/hosts"
- "/etc/services"
- "/etc/protocols"
- "/etc/resolv.conf"
- "/etc/ssl/openssl.cnf"
- "/etc/ssl/cert.pem"
- "/etc/group"
- "/etc/passwd"
- "/etc/localtime"
- "/bin/sh"
- "/usr/bin/ssh-keygen"
- "/usr/bin/openssl"
- "/usr/libexec/ld.so"
- "/usr/lib/libc.so.*"
- "/usr/lib/libutil.so.*"
- "/usr/lib/libcrypto.so.*"
- "/usr/lib/libz.so.*"
- "/usr/lib/libreadline.so.*"
- "/usr/lib/libcurses.so.*"
- "/usr/lib/libpthread.so.*"
- "/usr/lib/libc++.so.*"
- "/usr/lib/libc++abi.so.*"
- "/usr/lib/libm.so.*"
- "/usr/lib/libssl.so.*"
- "/usr/local/share/icu/{{versions.ICU_MAJOR}}.{{versions.ICU_MINOR}}/icudt*l.dat"
- "/usr/local/lib/libmemcached.so.*"
- "/usr/local/lib/libintl.so.*"
- "/usr/local/lib/libonig.so.*"
- "/usr/local/lib/libiconv.so.*"
- "/usr/local/lib/libxml2.so.*"
- "/usr/local/lib/liblzma.so.*"
- "/usr/local/lib/libsasl2.so.*"
- "/usr/local/lib/libmemcachedutil.so.*"
- "/usr/local/lib/libcurl.so.*"
- "/usr/local/lib/libpng16.so.*"
- "/usr/local/lib/libnghttp2.so.*"
- "/usr/local/lib/libjpeg.so.*"
- "/usr/local/lib/libicuuc.so.*"
- "/usr/local/lib/libicuio.so.*"
- "/usr/local/lib/libicui18n.so.*"
- "/usr/local/lib/libicudata.so.*"
- "/usr/X11R6/lib/libxcb.so.*"
- "/usr/X11R6/lib/libfreetype.so.*"
- "/usr/X11R6/lib/libXpm.so.*"
- "/usr/X11R6/lib/libXdmcp.so.*"
- "/usr/X11R6/lib/libXau.so.*"
- "/usr/X11R6/lib/libX11.so.*"
